#!/bin/sh
# BEGIN Qoder AI tracker
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd -W 2>/dev/null || pwd)"
"/usr/bin/node" "/home/zysong/.qoder-cn/remote/protocol-v1/installs/0.3.3/linux-x64-gnu.1789732196.2047613/lib/qoder-worker-runtime/qoder-worker-runtime.obf.mjs" commit --hook --workspace "$repo_root" 2>/dev/null || true
# END Qoder AI tracker
